# new configuration for docs since 1.3.0 to prevent from timeouts
version: 2

formats: [html]
sphinx:
   configuration: docs/conf.py
python:
   install:
     - requirements: docs/requirements.txt
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    build:
      html:
        - run: echo "Building the documentation..."
        - run: mkdir $READTHEDOCS_OUTPUT/html
        - run: python3 -m sphinx.cmd.build  -T -b html -d docs/_build/doctrees/ -D language=en docs/ $READTHEDOCS_OUTPUT/html