# new configuration for docs since 1.3.0 to prevent from timeouts
version: 2

sphinx:
   configuration: docs/conf.py
python:
   install:
     - requirements: docs/requirements.txt
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    build:
      html:
        - echo "Copying offline built documentation..."
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - cp -r docs/build/html/* $READTHEDOCS_OUTPUT/html