name: nrv-e
channels:
  - conda-forge
dependencies:
  - python==3.12
  - pip
  - fenics-dolfinx==0.9.0
  - mpich
  - python-gmsh
  - ipykernel
  - pip:
    - build
    - sphinx
    - sphinx-rtd-theme
    - furo
    - Pygments
    - sphinx-mdinclude
    - sphinx_copybutton
    - sphinx_gallery
    - sphinx_codeautolink