name: nrv
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - mpi4py
  - fenics-dolfinx=0.9.0
  - libblas=*=*blis
  - python-gmsh
  - ipykernel
  - mpich
  - sysroot_linux-64=2.17
  - pip:
      - nrv-py