#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _AXNODE_reg(void);
extern void _CaPump_reg(void);
extern void _DNav18_reg(void);
extern void _KCa_reg(void);
extern void _NaCaPump_reg(void);
extern void _Nakpump_reg(void);
extern void _NakpumpSchild_reg(void);
extern void _Nav11_a_reg(void);
extern void _Nav16_a_reg(void);
extern void _RattayAberham_reg(void);
extern void _caextscale_reg(void);
extern void _caintscale_reg(void);
extern void _can_reg(void);
extern void _cat_reg(void);
extern void _extrapump_reg(void);
extern void _flut_motor_reg(void);
extern void _flut_sensory_reg(void);
extern void _h_reg(void);
extern void _k_ion_dynamics_reg(void);
extern void _ka_reg(void);
extern void _kaslow_reg(void);
extern void _kd_reg(void);
extern void _kdr_reg(void);
extern void _kdr_Tiger_reg(void);
extern void _kds_reg(void);
extern void _kf_reg(void);
extern void _kmtype_reg(void);
extern void _kna_reg(void);
extern void _ks_reg(void);
extern void _leak_reg(void);
extern void _leakSchild_reg(void);
extern void _mysa_motor_reg(void);
extern void _mysa_sensory_reg(void);
extern void _na3_reg(void);
extern void _na_ion_dynamics_reg(void);
extern void _naf_reg(void);
extern void _naf97_reg(void);
extern void _naf97mean_reg(void);
extern void _nahh_reg(void);
extern void _nas_reg(void);
extern void _nas97_reg(void);
extern void _nas97mean_reg(void);
extern void _nattxs_reg(void);
extern void _nav1p9_reg(void);
extern void _nax_reg(void);
extern void _node_motor_reg(void);
extern void _node_sensory_reg(void);
extern void _stin_motor_reg(void);
extern void _stin_sensory_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," \"AXNODE.mod\"");
    fprintf(stderr," \"CaPump.mod\"");
    fprintf(stderr," \"DNav18.mod\"");
    fprintf(stderr," \"KCa.mod\"");
    fprintf(stderr," \"NaCaPump.mod\"");
    fprintf(stderr," \"Nakpump.mod\"");
    fprintf(stderr," \"NakpumpSchild.mod\"");
    fprintf(stderr," \"Nav11_a.mod\"");
    fprintf(stderr," \"Nav16_a.mod\"");
    fprintf(stderr," \"RattayAberham.mod\"");
    fprintf(stderr," \"caextscale.mod\"");
    fprintf(stderr," \"caintscale.mod\"");
    fprintf(stderr," \"can.mod\"");
    fprintf(stderr," \"cat.mod\"");
    fprintf(stderr," \"extrapump.mod\"");
    fprintf(stderr," \"flut_motor.mod\"");
    fprintf(stderr," \"flut_sensory.mod\"");
    fprintf(stderr," \"h.mod\"");
    fprintf(stderr," \"k_ion_dynamics.mod\"");
    fprintf(stderr," \"ka.mod\"");
    fprintf(stderr," \"kaslow.mod\"");
    fprintf(stderr," \"kd.mod\"");
    fprintf(stderr," \"kdr.mod\"");
    fprintf(stderr," \"kdr_Tiger.mod\"");
    fprintf(stderr," \"kds.mod\"");
    fprintf(stderr," \"kf.mod\"");
    fprintf(stderr," \"kmtype.mod\"");
    fprintf(stderr," \"kna.mod\"");
    fprintf(stderr," \"ks.mod\"");
    fprintf(stderr," \"leak.mod\"");
    fprintf(stderr," \"leakSchild.mod\"");
    fprintf(stderr," \"mysa_motor.mod\"");
    fprintf(stderr," \"mysa_sensory.mod\"");
    fprintf(stderr," \"na3.mod\"");
    fprintf(stderr," \"na_ion_dynamics.mod\"");
    fprintf(stderr," \"naf.mod\"");
    fprintf(stderr," \"naf97.mod\"");
    fprintf(stderr," \"naf97mean.mod\"");
    fprintf(stderr," \"nahh.mod\"");
    fprintf(stderr," \"nas.mod\"");
    fprintf(stderr," \"nas97.mod\"");
    fprintf(stderr," \"nas97mean.mod\"");
    fprintf(stderr," \"nattxs.mod\"");
    fprintf(stderr," \"nav1p9.mod\"");
    fprintf(stderr," \"nax.mod\"");
    fprintf(stderr," \"node_motor.mod\"");
    fprintf(stderr," \"node_sensory.mod\"");
    fprintf(stderr," \"stin_motor.mod\"");
    fprintf(stderr," \"stin_sensory.mod\"");
    fprintf(stderr, "\n");
  }
  _AXNODE_reg();
  _CaPump_reg();
  _DNav18_reg();
  _KCa_reg();
  _NaCaPump_reg();
  _Nakpump_reg();
  _NakpumpSchild_reg();
  _Nav11_a_reg();
  _Nav16_a_reg();
  _RattayAberham_reg();
  _caextscale_reg();
  _caintscale_reg();
  _can_reg();
  _cat_reg();
  _extrapump_reg();
  _flut_motor_reg();
  _flut_sensory_reg();
  _h_reg();
  _k_ion_dynamics_reg();
  _ka_reg();
  _kaslow_reg();
  _kd_reg();
  _kdr_reg();
  _kdr_Tiger_reg();
  _kds_reg();
  _kf_reg();
  _kmtype_reg();
  _kna_reg();
  _ks_reg();
  _leak_reg();
  _leakSchild_reg();
  _mysa_motor_reg();
  _mysa_sensory_reg();
  _na3_reg();
  _na_ion_dynamics_reg();
  _naf_reg();
  _naf97_reg();
  _naf97mean_reg();
  _nahh_reg();
  _nas_reg();
  _nas97_reg();
  _nas97mean_reg();
  _nattxs_reg();
  _nav1p9_reg();
  _nax_reg();
  _node_motor_reg();
  _node_sensory_reg();
  _stin_motor_reg();
  _stin_sensory_reg();
}
