#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/Applications/NEURON-7.8"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/Applications/NEURON-7.8/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/louisregnacq/Dropbox/Work/Model/NRV/NRV/nrv/mods/x86_64/.libs/libnrnmech.so" "$@"
