name: Use GitHub App token

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: "master | staging | dev"
        required: true
        type: string

jobs:
  run-with-app:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout with app token
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Who am I
        run: gh api /user
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}