name: Coordination -- master branch

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: coordination-master-${{ github.ref }}
  cancel-in-progress: false

jobs:
  prepare_release:
    name: prepare_release
    uses: ./.github/workflows/prepare_releasem.yml
    secrets: 
        APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        NRV_TOKEN_GITHUB: ${{ secrets.NRV_TOKEN_GITHUB }}

  publish_pypi:
    name: publish_pypi
    needs: prepare_release
    uses: ./.github/workflows/step_master_pypi_release.yml
    with:
      git_ref: ${{ needs.prepare_release.outputs.release_tag }}
    secrets: inherit

  create_release:
    name: create_release
    needs:
      - prepare_release
      - publish_pypi
    uses: ./.github/workflows/step_master_create_release.yml
    with:
      release_tag: ${{ needs.prepare_release.outputs.release_tag }}
    secrets: inherit

  publish_stable_docs:
    name: publish_stable_docs
    needs:
      - prepare_release
      - create_release
    uses: ./.github/workflows/step_master_publish_stable_docs.yml
    with:
      release_tag: ${{ needs.prepare_release.outputs.release_tag }}
      rtd_project: nrv
    secrets: inherit

  docker_images:
    name: docker_images
    needs:
      - prepare_release
      - create_release
      - publish_stable_docs
    uses: ./.github/workflows/step_master_docker-image.yml
    with:
      release_tag: ${{ needs.prepare_release.outputs.release_tag }}
    secrets: inherit
