name: Coordination -- staging branch

on:
  pull_request:
    branches:
      - staging
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - staging
  merge_group:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: coordination-staging-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  unit:
    name: unit
    uses: ./.github/workflows/step_staging_pytest-unit.yml

  e2e:
    name: e2e
    needs: unit
    uses: ./.github/workflows/step_staging_pytest-e2e.yml

  docs_latest:
    name: docs_latest
    needs: e2e
    uses: ./.github/workflows/step_staging_prebuild_docs.yml
    with:
      target_ref: staging
      rtd_project: nrv
      rtd_version: latest
    secrets: 
        APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        NRV_TOKEN_GITHUB: ${{ secrets.NRV_TOKEN_GITHUB }}

  publish_testpypi:
    name: publish_testpypi
    needs: docs_latest
    uses: ./.github/workflows/step_staging_testpypi_release.yml
    secrets: inherit

  deployment_test:
    name: deployment_test
    needs: publish_testpypi
    uses: ./.github/workflows/step_staging_pytest-deployment.yml

  merge_to_master:
    name: merge_to_master
    needs: deployment_test
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/step_staging_merge_to_master.yml
    secrets: 
        APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        NRV_TOKEN_GITHUB: ${{ secrets.NRV_TOKEN_GITHUB }}