name: Build and Push Docker Image on Release

#on:
#  release:
#    types: [published]


#!! FOR DEBUG ONLY 
on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU (for multi-arch)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/nrv/Dockerfile
        push: true
          #tags: nrvframework/nrv:latest, nrvframework/nrv:${{ github.event.release.tag_name }}
        tags: nrvframework/nrv:latest, nrvframework/nrv:${{'dev'}} #!! FOR DEBUG ONLY 
        platforms: linux/amd64,linux/arm64
