name: Pytest -- Run end-to-end (e2e) tests

# on:
#   workflow_dispatch:
#   pull_request:
#     branches:
#       - master
#       - dev
#     paths:
#       - ".github/workflows/pytest-e2e.yml"
#       - "conda/tests-env.yaml"
#       - "pyproject.toml"
#       - "nrv/**"
#       - "test/**"
#       - "tests/unitary_tests/sources/**"
# Debug option
on:
  push: 
    branches:
      - testability

permissions:
  contents: read

concurrency:
  group: pytest-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: self-hosted

    env:
      MAMBA_ROOT_PREFIX: /home/runner/micromamba
      ENV_NAME: nrv-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Miniconda with mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-variant: Miniforge3
          mamba-version: "*"
          auto-activate-base: false


      - name: Check micromamba
        run: |
          echo "MAMBA_ROOT_PREFIX=$MAMBA_ROOT_PREFIX"
          micromamba info

      - name: Create or update tests environment
        run: |
          if micromamba env list | grep -qE '(^|[[:space:]])'"$ENV_NAME"'([[:space:]]|$)'; then
            micromamba env update -n "$ENV_NAME" -f conda/test-env.yaml
          else
            micromamba create -y -f conda/tests-env.yaml
          fi

      - name: Run end-to-end tests
        shell: bash -el {0}
        run: |
          conda run -n nrv-tests python -m pytest test/e2e -q
