name: Release -- Bump Version

on:
  workflow_call:
    inputs:
      bump_type:
        description: "patch | minor | major"
        required: true
        type: string

permissions:
  contents: write # Job-level permissions configuration starts here

jobs:
  print-username:
    name: bump_version
    runs-on: ubuntu-latest

    steps:
      - name: Version bump type
        run: echo Performing ${{ inputs.bump_type }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0          # get all history for tags
            ref: dev       # change branch if needed
      - name: Setup git user
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Bump version
        run: |
            pip install bump2version
            bump2version ${{ inputs.bump_type }}
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.NRV_TOKEN_GITHUB }}
        run: |
          git push origin dev
        #   git push origin dev --tags
